name: untitled1
description: "Visual Agent AI hybrid view application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:

  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  flutter_feather_icons: ^2.0.0+1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.1.7  # 최신 버전 확인 후 사용
  google_fonts: ^6.2.1
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.4.4
  flutter_local_notifications: ^18.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/images/exona_logo.png" # 원하는 아이콘 경로
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/resized_icon.png
    - assets/images/exona_logo.png
    - assets/images/splash_background.png
    - assets/images/


